version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ktr0731/grpc-web-go-client
    docker:
      - image: circleci/golang:1.10.3

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure

      - run:
          name: build
          command: CGO_ENABLED=0 go build ./grpcweb

      - run:
          name: test
          command: CGO_ENALBED=0 go test -v -race ./grpcweb
